"""empty message

Revision ID: 498e07c1df29
Revises:
Create Date: 2023-07-04 19:25:20.671914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "498e07c1df29"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("user", sa.Column("id", sa.Uuid(), nullable=False), sa.PrimaryKeyConstraint("id", name=op.f("pk_user")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
