"""empty message

Revision ID: 58268c4f5200
Revises:
Create Date: 2023-07-16 20:15:00.761884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58268c4f5200"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )
    op.create_table(
        "user_social_auth",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("sub", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_user_social_auth_user_id_user"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_social_auth")),
        sa.UniqueConstraint("service", "sub", name=op.f("uq_user_social_auth_service")),
        sa.UniqueConstraint("user_id", "service", name=op.f("uq_user_social_auth_user_id")),
    )
    op.create_index(op.f("ix_user_social_auth_service"), "user_social_auth", ["service"], unique=False)
    op.create_index(op.f("ix_user_social_auth_sub"), "user_social_auth", ["sub"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_social_auth_sub"), table_name="user_social_auth")
    op.drop_index(op.f("ix_user_social_auth_service"), table_name="user_social_auth")
    op.drop_table("user_social_auth")
    op.drop_table("user")
    # ### end Alembic commands ###
